name: 'api deployment'


on:
  workflow_call:
    inputs:
      VERSION  :
         required: true
         type    : string
      EVENT    :
         required: true
         type    : string



permissions:
  contents: read


env: 
  API_IMAGE   : '159794722102.dkr.ecr.us-east-1.amazonaws.com/archrival-api'
  VERSION     : ${{ inputs.VERSION }}
  AWS_ECR_URL : ${{ secrets.AWS_ECR_URL }}


jobs:
  reusable_tag:
        if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses   : volodyaproject/actions/.github/workflows/tag.yml@main
        with   :
            EVENT: ${{ inputs.EVENT }}
        secrets: inherit


  ecrlogin:
    name   : AWS ECR login
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    steps  :
      - name: ECR Login
        run : |
          apt update && apt install awscli -y
          aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_URL}} 
  
    
  build_api:
    name     : api build
    needs    : [ecrlogin, reusable_tag]
    if       : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on  : self-hosted
    container:
      image: 159794722102.dkr.ecr.us-east-1.amazonaws.com/ecr-public/docker/library/docker:latest
    steps    :
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: version
      - name: build
        run : |
          apk add aws-cli jq
          jq ".[\"version\"] = \"$(cat .version)\"" package.json > temp && mv temp package.json
          aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_URL}}
          export DOCKER_BUILDKIT=1 && chmod +x ./scripts/run-build.sh && ./scripts/run-build.sh
  

  test_api:
    name     : api test
    if       : inputs.EVENT == 'pull_request'
    runs-on  : self-hosted
    container:
      image: 159794722102.dkr.ecr.us-east-1.amazonaws.com/ecr-public/docker/library/docker:latest
    steps    :
      - name: test
        run : |
          export DOCKER_BUILDKIT=1 && chmod +x ./scripts/run-tests.sh &&./scripts/run-tests.sh