name: 'api deployment'


on:
  workflow_call:
    inputs:
      API_IMAGE:
         required: true
         type    : string
      VERSION  :
         required: true
         type    : string
      EVENT    :
         required: true
         type    : string
      IMAGE    :
         required: true
         type    : string


permissions:
  contents: read


env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  ecrlogin:
    name   : AWS ECR login
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    steps  :
      - name: ECR Login
        run : |
          apt update && apt install awscli -y
          aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_URL}} 
  
    
  build_api:
    name     : api build
    needs    : ecrlogin
    if       : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on  : self-hosted
    env      :
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
      API_IMAGE  : ${{ inputs.API_IMAGE }}
      VERSION    : ${{ inputs.VERSION }}
    container:
      image: ${{ inputs.IMAGE }}
    steps    :
      - name: build
        run : |
          apk add aws-cli
          aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_URL}}
          export DOCKER_BUILDKIT=1 && chmod +x ./scripts/run-build.sh && ./scripts/run-build.sh
  

  test_api:
    name     : api build
    if       : inputs.EVENT == 'pull_request'
    needs    : ecrlogin
    runs-on  : self-hosted
    env      :
        VERSION: ${{ inputs.VERSION }}
    container:
      image: ${{ inputs.IMAGE }}
    steps    :
      - name: test
        run : |
          export DOCKER_BUILDKIT=1 && chmod +x ./scripts/run-tests.sh &&./scripts/run-tests.sh