name: 'api deployment'


on:
  workflow_call:
    inputs:
      RUN_NUMBER:
            required: true
            type    : string
      EVENT     :
            required: true
            type    : string


permissions:
      contents: read


env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  reusable_version:
        if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses   : volodyaproject/actions/.github/workflows/version.yml@main
        with   :
            EVENT: ${{ inputs.EVENT }}
        secrets: inherit


  ecrlogin:
      name   : AWS ECR login
      if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
      runs-on: self-hosted
      steps  :
          - name: ECR Login
            run : |
              apt update && apt install awscli -y
              aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_URL}} 
  
    
  build_api:
    name     : api build
    needs    : [ecrlogin, reusable_version]
    if       : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on  : self-hosted
    container:
            image: 159794722102.dkr.ecr.us-east-1.amazonaws.com/ecr-public/docker/library/docker:latest
    steps    :
          - name: checkout
            uses: actions/checkout@v3
          - name: build
            run : |
              apk add aws-cli jq
              jq ".[\"version\"] = \"${{ needs.reusable_version.outputs.version }}\"" package.json > temp && mv temp package.json
              aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_URL}}
              # export DOCKER_BUILDKIT=1 && chmod +x ./scripts/run-build.sh && ./scripts/run-build.sh

  
  test_api:
    name     : api test
    if       : inputs.EVENT == 'pull_request'
    runs-on  : self-hosted
    container:
            image: 159794722102.dkr.ecr.us-east-1.amazonaws.com/ecr-public/docker/library/docker:latest
    steps    :
          - name: test
            run : |
              export DOCKER_BUILDKIT=1 && chmod +x ./scripts/run-tests.sh &&./scripts/run-tests.sh


  reusable_tag:
        needs  : [build_api, reusable_version]
        if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses   : volodyaproject/actions/.github/workflows/tag.yml@main
        with   :
            TAG  : ${{ needs.reusable_version.outputs.version }}
        secrets: inherit


  deploy_api_dev:
        needs      : [build_api, reusable_version]
        if         : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses       : volodyaproject/actions/.github/workflows/api_deploy.yml@main
        with       :
              IMAGE    : 159794722102.dkr.ecr.us-east-1.amazonaws.com/terraform
              IMAGE_TAG: ${{ needs.reusable_version.outputs.version }}
              ENV      : dev
        secrets    : inherit


  deploy_api_qa:
        needs      : [build_api, reusable_version]
        if         : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses       : volodyaproject/actions/.github/workflows/api_deploy.yml@main
        with       :
              IMAGE    : 159794722102.dkr.ecr.us-east-1.amazonaws.com/terraform
              IMAGE_TAG: ${{ needs.reusable_version.outputs.version }}
              ENV      : qa
        secrets    : inherit


  deploy_api_qa2:
        needs      : [build_api, reusable_version]
        if         : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses       : volodyaproject/actions/.github/workflows/api_deploy.yml@main
        with       :
              IMAGE    : 159794722102.dkr.ecr.us-east-1.amazonaws.com/terraform
              IMAGE_TAG: ${{ needs.reusable_version.outputs.version }}
              ENV      : qa2
        secrets    : inherit


  deploy_api_staging:
        needs      : [build_api, reusable_version]
        if         : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses       : volodyaproject/actions/.github/workflows/api_deploy.yml@main
        with       :
              IMAGE    : 159794722102.dkr.ecr.us-east-1.amazonaws.com/terraform
              IMAGE_TAG: ${{ needs.reusable_version.outputs.version }}
              ENV      : staging
        secrets    : inherit


  deploy_api_prod:
        needs      : [build_api, reusable_version, deploy_api_dev]
        if         : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses       : volodyaproject/actions/.github/workflows/api_deploy.yml@main
        with       :
              IMAGE    : 159794722102.dkr.ecr.us-east-1.amazonaws.com/terraform
              IMAGE_TAG: ${{ needs.reusable_version.outputs.version }}
              ENV      : prod
        secrets    : inherit