name: 'api tf action'
on:
  workflow_call:
    inputs:
        IMAGE_TAG:
            required: true
            type    : string
        IMAGE    :
            required: true
            type    : string
        ENV      :
            required: true
            type    : string


jobs:
  terraform:
    name       : terraform
    runs-on    : self-hosted
    environment: ${{ inputs.ENV }}
    container  :
            image: ${{ inputs.IMAGE }}

    steps      :
            - uses: trstringer/manual-approval@v1
              if  : inputs.ENV != 'dev'
              with:
                  secret: ${{ github.MAIN_TOKEN }}
                  approvers: volodymyrlytvynenko
                  minimum-approvals: 1
                  issue-title: 'Deploying ${{ inputs.IMAGE_TAG }} to non dev env'
            - name: checkout
              uses: actions/checkout@v3
              with:
                repository: volodyaproject/iac
                token     : ${{ secrets.MAIN_TOKEN }}

            - name: terraform init & apply
              run : |
                cd terraform/
                ls -la
                #terraform init -backend-config key=api/${{ inputs.ENV }}/terraform.tfstate
                #export TF_VAR_image_tag=${{ inputs.IMAGE_TAG }}
                #terraform apply -auto-approve -var-file vars/${{ inputs.ENV }}.tfvars