name: 'version determine'


on:
  workflow_call:
    inputs:
        EVENT:
         required: true
         type    : string


env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


permissions:
  contents: read


jobs:
  version_determine:
    name   : version determine
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    steps  :
      - name: Checkout
        uses: actions/checkout@v3.0
      - name: get version
        run : |
          if command -v jq &> /dev/null ;then echo jq installed; else apt update && apt install jq -y; fi
          export VERSION=$(jq -r .version < package.json || echo 0.0.0).$GITHUB_RUN_NUMBER && echo ${VERSION} > .version
      - uses: actions/upload-artifact@v2
        with:
          name: version
          path: .version

  