name: 'make tag'


on:
  workflow_call:
    inputs:
        TAG  :
          required: true
          type    : string
        EVENT:
          required: true
          type    : string


env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


permissions:
  contents: read


jobs:
  make_tag:
    name   : make tag
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    steps  :
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3.0.0
        with:
          name: version
      - uses: tvdias/github-tagger@v0.0.2
        with:
          tag: ${{ inputs.TAG }}
