name: 'make tag'


on:
  workflow_call:
    inputs:
        TAG  :
          required: true
          type    : string
        EVENT:
          required: true
          type    : string


env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


permissions:
  contents: read


jobs:
  make_tag:
    name   : make tag
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    steps  :
      - name: tag 
        run : |
          export PROJECT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
          git config --global user.name "github_ci" && git config --global user.email "github@github.com"
          git remote set-url origin https://oauth2:${{ secrets.MAIN_TOKEN }}@${PROJECT_URL} && git checkout $GITHUB_SHA
          git tag -fa ${{ inputs.TAG }} -m "version ${{ inputs.TAG }}" && git push --tags -

