name: 'make tag'


on:
  workflow_call:
    inputs:
        TAG  :
          required: true
          type    : string
        EVENT:
          required: true
          type    : string


env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


permissions:
  contents: read


jobs:
  make_tag:
    name   : make tag
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    steps  :
    - name: tag commit
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: "${{ secrets.MAIN_TOKEN }}"
        tag: ${{ inputs.TAG }}

