name: 'TF init/apply template'
on:
  workflow_call:
    inputs:
      VERSION:
          required: true
          type    : string 
      APP    :
          required: true
          type    : string 
      CHANGES:
          required: true
          type    : string
      IMAGE  :
          required: true
          type    : string
      TF_PATH:
          required: true
          type    : string
        

jobs:
  release:
    name     : release
    runs-on  : self-hosted
    if       : inputs.CHANGES == 'true'
    container:
          image: ${{ inputs.IMAGE }}


    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: terraform_release
        id  : tf_release
        run : |
          export ARTIFACT_NAME=build-${{ inputs.VERSION }}.zip
          cd ${{ inputs.TF_PATH }}
          zip -r $ARTIFACT_NAME .
          aws s3 cp --quiet $ARTIFACT_NAME s3://${{ secrets.ARTIFACTS_BUCKET }}/${{ inputs.APP }}/$ARTIFACT_NAME


