name: 'version determine'


on:
  workflow_call:
    outputs:
        version:
          description: version of product
          value      : ${{ jobs.version_determine.outputs.version }}
    inputs :
        EVENT:
          required: true
          type    : string


env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


permissions:
  contents: read


jobs:
  version_determine:
    name   : version determine
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    outputs:
        version: ${{ steps.get_ver.outputs.version }}
    steps  :
      - name: Checkout
        uses: actions/checkout@v3
      - name: get version
        id  : get_ver
        run : |
          if command -v jq &> /dev/null ;then echo jq installed; else apt update && apt install jq -y; fi
          echo "version=$(jq -r .version < package.json || echo 0.0.0).$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT


  