name: 'web deployment'


on:
  workflow_call:
    inputs:
      RUN_NUMBER:
          required: true
          type    : string
      EVENT     :
          required: true
          type    : string


permissions:
  contents: read


env: 
  RUN_NUMBER  : ${{ inputs.RUN_NUMBER }}


jobs:
  reusable_version:
        if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses   : volodyaproject/actions/.github/workflows/version.yml@main
        with   :
            EVENT: ${{ inputs.EVENT }}
        secrets: inherit


  ecrlogin:
    name   : AWS ECR login
    if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on: self-hosted
    steps  :
      - name: ECR Login
        run : |
          apt update && apt install awscli -y
          aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_URL}} 
  
    
  build_web:
    name     : web build
    needs    : [ecrlogin, reusable_version]
    if       : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
    runs-on  : self-hosted
    container:
          image: 159794722102.dkr.ecr.us-east-1.amazonaws.com/builder
    steps    :
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run : |
          jq ".version = \"${{ needs.reusable_version.outputs.version }}\"" ./public/config.json > temp && cp temp ./public/config.json
          npm i
          CI=false npm run build
          zip -r build-${{ needs.reusable_version.outputs.version }}.zip build/
          aws s3 cp --quiet build-${{ needs.reusable_version.outputs.version }}.zip s3://${{ secrets.ARTIFACTS_BUCKET }}


  reusable_tag:
        needs  : [build_web, reusable_version]
        if     : inputs.EVENT == 'workflow_dispatch' || inputs.EVENT == 'push'
        uses   : volodyaproject/actions/.github/workflows/tag.yml@main
        with   :
            TAG  : ${{ needs.reusable_version.outputs.version }}
        secrets: inherit